# Generated by Django 3.2.7 on 2021-10-01 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='削除日時')),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
