# Generated by Django 3.2.7 on 2021-10-17 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='index_keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.index'),
        ),
    ]
