# Generated by Django 3.2.7 on 2021-10-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='url_json',
            new_name='index_json',
        ),
    ]
