# Generated by Django 3.2.7 on 2021-10-16 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToAnalyzePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='削除日時')),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
