# Generated by Django 3.2.7 on 2021-10-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
